# Generated by Django 2.1.7 on 2019-04-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, null=True)),
                ('last_name', models.CharField(max_length=20, null=True)),
                ('username', models.CharField(max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=17)),
                ('email_id', models.EmailField(blank=True, max_length=254, unique=True)),
                ('date_birth', models.CharField(max_length=10, null=True)),
                ('password', models.CharField(max_length=20, null=True)),
                ('confirm_password', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
