# Generated by Django 2.1.7 on 2019-04-28 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homepagetext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_flag_tex', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Hotelrooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wel_home_text', models.CharField(max_length=50, null=True)),
                ('hotel_name', models.CharField(max_length=50, null=True)),
                ('home_text', models.CharField(max_length=20, null=True)),
                ('learn_text', models.CharField(max_length=20, null=True)),
                ('room_no_text', models.CharField(max_length=20, null=True)),
                ('day_price', models.IntegerField(max_length=20, null=True)),
                ('day_price_dis', models.IntegerField(max_length=20, null=True)),
                ('month_price', models.IntegerField(max_length=20, null=True)),
                ('mont_price_dis', models.IntegerField(max_length=20, null=True)),
                ('profile_text', models.CharField(blank=True, max_length=17)),
                ('room_flag', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, null=True)),
                ('last_name', models.CharField(max_length=20, null=True)),
                ('username', models.CharField(max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=17)),
                ('email_id', models.EmailField(blank=True, max_length=254, unique=True)),
                ('date_birth', models.CharField(max_length=10, null=True)),
                ('password', models.CharField(max_length=8, null=True)),
                ('confirm_password', models.CharField(max_length=8, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='homepagetext',
            name='hotel_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ImageAPP.Hotelrooms'),
        ),
    ]
