# Generated by Django 2.1.7 on 2019-04-27 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotelrooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_text', models.CharField(max_length=20, null=True)),
                ('learn_text', models.CharField(max_length=20, null=True)),
                ('room_no_text', models.CharField(max_length=20, null=True)),
                ('day_price', models.IntegerField(max_length=20, null=True)),
                ('day_price_dis', models.IntegerField(max_length=20, null=True)),
                ('month_price', models.IntegerField(max_length=20, null=True)),
                ('mont_price_dis', models.IntegerField(max_length=20, null=True)),
                ('profile_text', models.CharField(blank=True, max_length=17)),
            ],
        ),
        migrations.AlterField(
            model_name='signup',
            name='confirm_password',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='password',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
