# Generated by Django 2.1.7 on 2019-04-28 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageAPP', '0003_hotelrooms_room_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelrooms',
            name='hotel_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
