# Generated by Django 2.1.7 on 2019-04-28 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageAPP', '0004_hotelrooms_hotel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelrooms',
            name='hotel_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
