# Generated by Django 2.1.7 on 2019-04-28 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ImageAPP', '0005_auto_20190428_0047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homepagetext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ImageAPP.Hotelrooms')),
            ],
        ),
    ]
