# Generated by Django 2.1.7 on 2019-04-28 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageAPP', '0006_homepagetext'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelrooms',
            name='wel_home_text',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
